spring:
  application:
    name: User-service
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9083